apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: project9-restart-rollback-freeze
spec:
  args:
    - name: namespace
      value: project8-dev
    - name: window
      value: 2m
    - name: threshold
      value: "0"

  metrics:
    - name: restart-spike
      interval: 30s
      count: 4
      failureLimit: 0
      consecutiveErrorLimit: 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
          query: |
            sum(
              increase(
                kube_pod_container_status_restarts_total{namespace="{{args.namespace}}"}[{{args.window}}]
              )
            )
      successCondition: result[0] <= {{args.threshold}}
      failureCondition: result[0] > {{args.threshold}}

