apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project9-analysis-templates
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theseanchristopher/project9-aiops-reliability.git
    targetRevision: main
    path: manifests/analysis
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

